# Declare variables to be passed into your templates.

ClusterEnv: dev
ClusterName: tarantool-cluster
ClusterDomainName: cluster.local
TarantoolWorkDir: /var/lib/tarantool
LuaMemoryReserveMB: 0

image:
  repository: dyne/zenswarm-benchmark
  tag: 7100556519119b04b5192feee1100fd269312c54
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8081

Prometheus:
  port: 8081
  path: /metrics

RoleConfig:
  - RoleName: routers     # ReplicaSet name
    ReplicaCount: 1       # Number of replicas in each ReplicaSet
    ReplicaSetCount: 1    # Number of ReplicaSets for this role(s)
    DiskSize: 256Mi         # Persistent Volume disk sze
    CPUallocation: 0.10   # Number of vCPUs to allocate to each container
    MemtxMemoryMB: 256    # MB of memory to be assigned to each container
    RolesToAssign:
      - app.roles.custom

 #     - vshard-router

  - RoleName: storage
    ReplicaCount: 2
    ReplicaSetCount: 1
    DiskSize: 256Mi
    CPUallocation: 0.10
    MemtxMemoryMB: 256
    RolesToAssign:
      - app.roles.custom

 #     - vshard-storage
